#!/bin/sh

echo 0 > /sys/class/backlight/aml-bl/brightness
sleep 1
echo 1 > /sys/class/backlight/aml-bl/brightness
sleep 1
echo 0 > /sys/class/backlight/aml-bl/brightness
sleep 1
echo 1 > /sys/class/backlight/aml-bl/brightness
