#!/bin/sh

case "$1" in
	start)
		echo 32 > /sys/class/graphics/fb0/bits_per_pixel
        cat /opt/popes/pope.raw > /dev/fb0
		;;
	stop)
        cat /opt/popes/clr0.raw > /dev/fb0
		;;
	restart)
		"$0" stop
		sleep 5
		"$0" start
		;;
	reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac

exit 0
